
export const CREATE_TODO_REQUEST = "CREATE_TODO_REQUEST";
export const CREATE_TODO_SUCCESS = "CREATE_TODO_SUCCESS";
export const CREATE_TODO_FAILURE = "CREATE_TODO_FAILURE";

export const GET_TODOS_REQUEST = "GET_TODOS_REQUEST";
export const GET_TODOS_SUCCESS = "GET_TODOS_SUCCESS";
export const GET_TODOS_FAILURE = "GET_TODO_FAILURE";

export const MARK_TODO_DONE_REQUEST = "MARK_TODO_DONE_REQUEST";
export const MARK_TODO_DONE_SUCCESS = "MARK_TODO_DONE_SUCCESS";
export const MARK_TODO_DONE_FAILURE = "MARK_TODO_DONE_FAILURE";

export const DELETE_TODO_REQUEST = "DELETE_TODO_REQUEST";
export const DELETE_TODO_SUCCESS = "DELETE_TODO_SUCCESS";
export const DELETE_TODO_FAILURE = "DELETE_TODO_FAILURE";
