export const SIGN_UP_REQUEST = "SIGN_UP_REQUEST"
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS"
export const SIGN_UP_FAILURE = "SIGN_UP_FAILURE"

export const SIGN_IN_REQUEST = "SIGN_IN_REQUEST"
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS"
export const SIGN_IN_FAILURE = "SIGN_IN_FAILURE"

export const CREATE_TODO_REQUEST = "CREATE_TODO_REQUEST"
export const CREATE_TODO_SUCCESS = "CREATE_TODO_SUCCESS"
export const CREATE_TODO_FAILURE = "CREATE_TODO_FAILURE"

export const GET_TODOS_REQUEST = "GET_TODOS_REQUEST"
export const GET_TODOS_SUCCESS = "GET_TODOS_SUCCESS"
export const GET_TODOS_FAILURE = "GET_TODO_FAILURE"

export const MARK_TODO_DONE_REQUEST = "MARK_TODO_DONE_REQUEST"
export const MARK_TODO_DONE_SUCCESS = "MARK_TODO_DONE_SUCCESS"
export const MARK_TODO_DONE_FAILURE = "MARK_TODO_DONE_FAILURE"

export const DELETE_TODO_REQUEST = "DELETE_TODO_REQUEST"
export const DELETE_TODO_SUCCESS = "DELETE_TODO_SUCCESS"
export const DELETE_TODO_FAILURE = "DELETE_TODO_FAILURE"

export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE"
export const SET_PAGE_SIZE = "SET_PAGE_SIZE"

export const APP_THEME = "APP_THEME"
export const CHANGE_APP_THEME = "CHANGE_APP_THEME"

export const APP_LOCALE = "APP_LOCALE"
export const CHANGE_APP_LOCALE = "CHANGE_APP_LOCALE"
