export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST'
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS'
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE'

export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST'
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS'
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE'

export const PASSWORD_RECOVERY_STEP_1_REQUEST =
  'PASSWORD_RECOVERY_STEP_1_REQUEST'
export const PASSWORD_RECOVERY_STEP_1_SUCCESS =
  'PASSWORD_RECOVERY_STEP_1_SUCCESS'
export const PASSWORD_RECOVERY_STEP_1_FAILURE =
  'PASSWORD_RECOVERY_STEP_1_FAILURE'

export const PASSWORD_RECOVERY_STEP_2_REQUEST =
  'PASSWORD_RECOVERY_STEP_2_REQUEST'
export const PASSWORD_RECOVERY_STEP_2_SUCCESS =
  'PASSWORD_RECOVERY_STEP_2_SUCCESS'
export const PASSWORD_RECOVERY_STEP_2_FAILURE =
  'PASSWORD_RECOVERY_STEP_2_FAILURE'

export const SIGN_OUT = 'SIGN_OUT'
