export const OPEN_SOCKET_REQUEST = 'OPEN_SOCKET_REQUEST'
export const OPEN_SOCKET_SUCCESS = 'OPEN_SOCKET_SUCCESS'
export const OPEN_SOCKET_FAILURE = 'OPEN_SOCKET_FAILURE'

export const CLOSE_SOCKET = 'CLOSE_SOCKET'

export const GET_MESSAGE = 'GET_MESSAGE'
